name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build

    - name: Run tests
      run: |
        cargo test
        cd macros
        cargo test
        cd examples
        cargo test
        cargo run --package isomdl_examples --bin device_and_reader

    - name: Clippy
      run: |
        cargo clippy
        cd macros
        cargo clippy
        cd examples
        cargo clippy

    - name: Fmt
      run: |
        cargo fmt -- --check
        cd macros
        cargo fmt -- --check
        cd examples
        cargo fmt -- --check
