name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --all-targets

      - name: Run tests
        run: |
          cargo test
          cd macros
          cargo test

      - name: Run examples
        run: |
          skip_marker="#[spruce_example(run(skip=true))]"
          for example in examples/*.rs
          do
            if ! grep -q "$skip_marker" "$example"; then
              cargo run --example "$(basename "${example%.rs}")" -- $args
            fi
          done

      - name: Run scripts tests
        run: |
          test_sync_md_includes() {
          RED='\033[0;31m'
          local tmp="/tmp/test-md-includes"
          rm -rf "$tmp"
          local marker="test-42-42-42"
          mkdir "$tmp"
          echo "$marker" > "$tmp/test.rs"
          echo "<!-- INCLUDE-RUST: $tmp/test.rs -->" > "$tmp/test.md"
            echo '```rust' >> "$tmp/test.md"
            echo '```' >> "$tmp/test.md"
            ./scripts/sync-md-includes.sh "$tmp/test.md"
            if ! grep -q "$marker" "$tmp/test.md"; then
          echo "${RED}test failed: test_sync_md_includes"
            exit 1
            fi
          }
          test_sync_md_includes
          
          test_sync_rustdoc_includes() {
          RED='\033[0;31m'
          local tmp="/tmp/test-md-includes"
          rm -rf "$tmp"
          local marker="test-42-42-42"
          mkdir "$tmp"
          echo "$marker" > "$tmp/test.rs"
          echo "//! <!-- INCLUDE-RUST: $tmp/test.rs -->" > "$tmp/test2.rs"
            echo '/! ```' >> "$tmp/test2.rs"
            echo '//! ```' >> "$tmp/test2.rs"
            ./scripts/sync-rustdoc-includes.sh "$tmp"
            if ! grep -q "$marker" "$tmp/test2.rs"; then
          echo "${RED}test failed: test_sync_rustdoc_includes"
            exit 1
            fi
          }
          test_sync_rustdoc_includes

      - name: Clippy
        run: |
          cargo clippy --all-targets

      - name: Fmt
        run: |
          cargo fmt --all -- --check
