name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --all-targets

      - name: Run tests
        run: |
          cargo test
          cd macros
          cargo test

      - name: Run scripts tests
        run: ./scripts/test.sh

      - name: Run examples
        run: ./examples/run.sh

      - name: Clippy
        run: cargo clippy --all-targets

      - name: Fmt
        run: cargo fmt --all -- --check