name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --all-targets

      - name: Run tests
        run: |
          cargo test
          cd macros
          cargo test

          cd ..
          for example in examples/*.rs
          do
            cargo run --example "$(basename "${example%.rs}")" -- $args
          done

      - name: Clippy
        run: |
          cargo clippy --all-targets
          cd macros
          cargo clippy --all-targets

      - name: Fmt
        run: |
          cargo fmt --all -- --check
          cd macros
          cargo fmt --all -- --check
